# Schema for the configuration files of the Virtual_Datetime module.

field.storage_settings.virtual_datetime:
  type: mapping
  label: 'Virtual_Datetime settings'
  mapping:
    virtual_datetime_type:
      type: string
      label: 'Date type'

field.field_settings.virtual_datetime:
  type: mapping
  label: 'Virtual_Datetime settings'

field.value.virtual_datetime:
  type: mapping
  label: 'Default value'
  mapping:
    default_date_type:
      type: string
      label: 'Default date type'
    default_date:
      type: string
      label: 'Default date value'

field.formatter.settings.virtual_datetime_base:
  type: mapping
  mapping:
    timezone_override:
      type: string
      label: 'Time zone override'

field.formatter.settings.virtual_datetime_default:
  type: field.formatter.settings.virtual_datetime_base
  label: 'Virtual_Datetime default display format settings'
  mapping:
    format_type:
      type: string
      label: 'Date format'

field.formatter.settings.virtual_datetime_plain:
  type: field.formatter.settings.virtual_datetime_base
  label: 'Virtual_Datetime plain display format settings'

field.formatter.settings.virtual_datetime_custom:
  type: field.formatter.settings.virtual_datetime_base
  label: 'Virtual_Datetime custom display format settings'
  mapping:
    date_format:
      type: date_format
      label: 'Date/time format'

field.formatter.settings.virtual_datetime_time_ago:
  type: mapping
  label: 'Virtual_Datetime time ago display format settings'
  mapping:
    future_format:
      type: string
      label: 'Future format'
    past_format:
      type: string
      label: 'Past format'
    granularity:
      type: integer
      label: 'Granularity'

field.widget.settings.virtual_datetime_datelist:
  type: mapping
  label: 'Virtual_Datetime select list display format settings'
  mapping:
    increment:
      type: integer
      label: 'Time increments'
    date_order:
      type: string
      label: 'Date part order'
    time_type:
      type: string
      label: 'Time type'

field.widget.settings.virtual_datetime_default:
  type: mapping
  label: 'Virtual_Datetime default display format settings'
